### ISSUE TITLE
Meal/Restaurant Planning Task List

### ISSUE THREAD

**Issue by ajperkins92** [eawhite00/UWBootCampProject1#2]
##User Story
As a user, I want planning meals on my roadtrip to be done ahead of time. 

##Acceptance Criteria
- [ ] JavaScript includes Ajax request to Yelp API
- [ ] index.html includes a submit for destination that will constitute the Yelp Search
- [ ] index.html will display a set amount of results based off of the queried destination
- [ ] Each destination section has its own list of restaurants
