### ISSUE TITLE
Wikipedia Task List

### ISSUE THREAD

**Issue by ajperkins92** [eawhite00/UWBootCampProject1#3]
## User Story
As a user, I want to know more about the places that I'm visiting.

## Acceptance Criteria
 - [ ] JavaScript includes Ajax request to the Wikipedia API
  - [ ] index.html includes a submit for destination that will constitute the Wikepedia Search
  - [ ] index.html will display one result (as opposed to the set number of Yelp results) based off of the queried destination
  - [ ] Each destination section includes a paragraph or two from Wikipedia in its information section
